CONFIG_MODULE = "config"
CONVERSIONS_MODULE = "conversions"
DATABASE_MODULE = "database"
REST_API_MODULE = "rest_api"
SECURITY_MODULE = "security"
SYSTEM_MODULE = "system"
UTILITIES_MODULE = "utilities"
WEB_MODULE = "web"

MODULES = [
    CONFIG_MODULE,
    CONVERSIONS_MODULE,
    DATABASE_MODULE,
    REST_API_MODULE,
    SECURITY_MODULE,
    SYSTEM_MODULE,
    UTILITIES_MODULE,
    WEB_MODULE
]
